clean:
	# Remove all files generated by the build process in build
	@rm -rf build/libs

build-jar:
	./gradlew bootJar

PROJECT_NAME="f-lab-calorie-counter"
VERSION:=$(shell ls -t ./build/libs | grep "${PROJECT_NAME}" | head -n 1 | sed 's/.jar//')
FILE_NAME="./build/libs/${VERSION}.jar"
SERVER_PORT=9092

run:
	if [ -f ${FILE_NAME} ]; then \
		java -jar ${FILE_NAME} --server.port=${SERVER_PORT}; \
	else \
		echo "File not found: ${FILE_NAME}"; \
	fi
