server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  security:
    patterns:
      ignoring:
        GET: [ "/v1/**" ]
        POST: [ "/v1/**" ]
        PATCH: [ ]
        PUT: [ ]
        DELETE: [ ]
      permit-all:
        GET: [ "/v1/**" ]
        POST: [ ]
        PATCH: [ ]
        PUT: [ ]
        DELETE: [ ]
    jwt:
      issuer: jypthemiracle
      client-secret:
      accessToken:
        header: atoken
        expiry-seconds: 6000000
      refreshToken:
        header: rtoken
        expiry-seconds: 6000000
