spring:
  application:
    name: v1-service
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/calorie?serverTimezone=Asia/Seoul
    username: root
    password: root

eureka:
  instance:
    instanceId: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  application:
    name: v1-service
  config:
    activate:
      on-profile: "test"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: yj
    password:

eureka:
  instance:
    instanceId: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
---

spring:
  application:
    name: v1-service

# eureka
eureka:
  instance:
    instanceId: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-handlers-package: com.example.flabcaloriecounter.util
