server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  application:
    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/user/**
